### PR TITLE
Support any size splash on Linux

### PR DESCRIPTION
**Pull request by RhythmLunatic**
sure why not?

### CODE REVIEW

**Comment by dguzek** [comment]
What are the implications of this change?  Will the GTK loading window be sized to accommodate the size of the splash image?  What will happen when a theme uses a very small splash image or a very large splash or a splash with a peculiar dimension ratio?

I don't think I have strong feelings one way or the other; I'm mostly just curious.

**Comment by RhythmLunatic** [comment]
The loading window accommodates the size of the splash image. If the splash is huge it will make the window huge too and the window will go offscreen if it's bigger than the desktop.
If the splash is tiny (such as 10x10) the window cuts off the text at the end of the loading window and it looks like this. Maybe other DEs will behave differently.

screenshot

**Comment by dguzek** [comment]
Maybe I knew this at one point (I should, given that I submitted #613), but I guess LoadWindow_MacOSX.mm already supports this sort of thing.

I'm unable to follow along with [the relevant code](https://github.com/stepmania/stepmania/blob/7e3789b131bb5da143e2b069630440ea3e7043fb/src/arch/LoadingWindow/LoadingWindow_Win32.cpp#L29-L40) in LoadingWindow_Win32.cpp just by reading it, and I don't have Windows to empirically test on, but it's looking like some scaling/resizing to force a wider-than-tall aspect ratio always occurs.  While it's outside the scope of this PR, cross-platform consistency is good.  If I had a Windows build environment, I'd probably try just removing that block and seeing what happens.

Anyway, this seems fine.  Thanks for the pull request!

**Comment by dguzek** [comment]
Oops, just kidding.  I went to merge and realized that this needs to be rebased or redone following #1837.  Sorry about this!

**Comment by RhythmLunatic** [comment]
I don't entirely get what's going on in LoadingWindow_Win32 but when you use an oversize image it just draws over the entire window.

It looks like SetWindowPos is needed, like `SetWindowPos(NULL,(dialogWidth-rectCtrl.Width())/2,(dialogHeight-rectCtrl.Height())/2,0,0,SWP_NOSIZE | SWP_NOZORDER);` (example code I took from googling)

I'll look into it later.

**Comment by dguzek** [comment]
> I'll look into it later.

If you'd like to and have time, that would be appreciated.  

If you'd like to just redo the two lines that changed in this commit to resolve the new conflicts, I can merge that for now.

**Pull request closed without merging**
