### PR TITLE
Remove unused function.

### PR DESCRIPTION
**Pull request by wolfman2000**
Is there really a point for us to have this?

### CODE REVIEW

**Comment by roothorick** [comment]
The ArchHooks_MacOSX impl looks like a misinterpretation of the function's intent to me, based on what ArchHooks_Win32 does. Is something else pulling the OS version?

**Comment by wolfman2000** [comment]
@roothorick The question is unclear. There were no public or private calls made to `GetMachineId`. What would pull it?

**Comment by roothorick** [comment]
Clearly that info comes from somewhere else then, as it's showing up in the crashinfo.

The build failure looks like a Travis internal problem. GCC passed.

Okay, +1

**Comment by shakesoda** [comment]
assigning @dguzek since OS X is the only thing to check here, I think, will merge on feedback

**Comment by dguzek** [comment]
It built fine for me. :+1:

**Pull request merged**
