### PR TITLE
Add Bahasa Indonesia to _fallback theme

### PR DESCRIPTION
**Pull request by JOELwindows7**
Another file for fallback language picking which applies to all theme that reffers fallback
Incomplete yet!

### CODE REVIEW

**Comment by kyzentun** [comment]
How do you want your name written in the credits file?

**Comment by JOELwindows7** [comment]
I would like be like this:
Translator
....
5.1 Update
.....
Joel Robert Justiawan (JOELwindows7)
......

and don't forget, the Shoutout:
.......
Perkedel Corporation
.......

Because I am the founder of Perkedel Corporation, technically, helped for my people around here.

**Comment by JOELwindows7** [comment]
Be patient! these strings are so many!

**Comment by JOELwindows7** [comment]
Update started for SM5.1!

**Comment by Scraticus** [comment]
Closing due to 5.2, and it's abandoned

**Pull request closed without merging**
