### PR TITLE
well needed update for the song instruction

### PR DESCRIPTION
**Pull request by TheKamilia**
wish i had this when i first started playing stepmania

### CODE REVIEW

**Comment by ListenerJubatus** [comment]
There's legal issues with doing this, imo.

**Comment by TheKamilia** [comment]
> There's legal issues with doing this, imo.

how?

**Comment by coderjo** [comment]
I'm not sure how settled in court this is, but there have been court cases where merely linking to materials that being distributed without a license has been argued to be contributory copyright infringement.

**Comment by TheKamilia** [comment]
> I'm not sure how settled in court this is, but there have been court cases where merely linking to materials that are being distributed without a license has been argued to be contributory copyright infringement.

They have song packs on there website...

**Comment by shakesoda** [comment]
I dunno if this is actually problematic but I'm gonna leave this bag of worms closed.

I agree that better ways to help users find content would be good in the long run though, I'd like to improve the package manager in the game client, and have the it ask stepmania.com for an index of contributed repository addresses (+ allow adding them manually).

**Comment by TheKamilia** [comment]
> I dunno if this is actually problematic but I'm gonna leave this bag of worms closed.

I agree that better ways to help users find content would be good in the long run though, I'd like to improve the package manager in the game client, and have it ask stepmania.com for an index of contributed repository addresses (+ allow adding them manually).

etterna managed to do it if you compile there lasted test build

**Pull request closed without merging**
