### PR TITLE
Update gtk+ LoadingWindow to use gtk3

### PR DESCRIPTION
**Pull request by leftmostcat**
Primarily changes against CMake, with one change to the code to remove a deprecated symbol. Built and briefly tested. No visible issues. (Redo of #744 against 5_1_0.)

### CODE REVIEW

**Comment by Prcuvu** [comment]
You possibly need to replace `libgtk2.0-dev` with `libgtk-3-dev` in `.travis.yml` to pass Travis CI build check.

**Comment by leftmostcat** [comment]
Thanks, this slipped my mind. When I made the PR, the build failure was unrelated to my changes, so I glossed over it. I'll update the PR later today.

**Comment by wolfman2000** [comment]
@leftmostcat Have you considered updating or redoing this PR?

**Comment by wolfman2000** [comment]
I gave this branch a shot. After cherry-picking the commit and updating it with minor fixes, I ran into a crash before the loading window was supposed to show up.  http://pastebin.com/L9X2C9vw

The crashinfo itself is found here: http://pastebin.com/pmbNXpxA

I'm wondering if it crashed due to the version mismatch of libpng. Apparently ubuntu prefers to only supply libpng 1.2 when we need 1.5.

This may require additional investigation.

**Comment by kyzentun** [comment]
This needs to be rebased now that 5.1 has been merged into master.

**Pull request closed without merging**
