### PR TITLE
Integrate C++11 Branch into 5_1-new

### PR DESCRIPTION
**Pull request by teejusb**
The general things from wolfman2000's commits seem to be:

- Deprecation of the Foreach.h header in favor of C++11 style range-for loops
- Upgrading to use std::unique_ptr in favor of the deprecated std::auto_ptr
- Using nullptr (or nil for Objective-C *.mm files) in favor of NULL

No new commits than those in the C++11 Branch, but there are some slight modifications when addressing the merge conflicts.

Tested on Ubuntu (played through a song without issues, also no Build warnings now :D)

Sorry for big boy Pull Request xP

### CODE REVIEW

**Comment by teejusb** [comment]
Oof I thought the diff was originally very large (+19k/-21k) due to line endings, so I normalized them to Unix style and it turns out that the codebase had a huge split to begin with! And now the diff is even worse (+69k/-70k). Let me know if you want me to do revert the normalization commit for the sake of progress on the PR and then re-create it for a future PR.

image

**Comment by RyTak** [comment]
Make sure to check that it passes building for MacOS, as we do have a userbase playing on that platform.

**Comment by teejusb** [comment]
Travis seems a bit happier now. It builds with gcc but is still failing with clang, which was the case before this PR.

https://travis-ci.org/stepmania/stepmania/branches

And will do.

**Comment by teejusb** [comment]
MacOS build passes: built with XCode 10.2.1 on Mojave.

**Comment by dguzek** [comment]
Thanks for working on this, @teejusb!  🎉 

I am in favor of resetting back to de29ba656b087f29146738d2eeec1c419ef63a26 so as not to include 85e68510665fc06834bb14e80cbdfbab760290c7.  `git blame` can be useful and running dos2unix on`./` has a way of resetting that.

If you want:
```
git reset --hard de29ba656b087f29146738d2eeec1c419ef63a26
```

It's worth noting that ~20k of the ~70k changed lines came from libtomcrypt and libtommath alone.  Fewer StepMania-specific src files were touched than I anticipated, so I am okay with this getting merged as-is.  Ultimately, I don't think the StepMania project is in a position to be turning down good pull requests.  🙂

I'm interested to see if @shakesoda has any feedback on any of this.

**Comment by teejusb** [comment]
Reverted the line-normalization commit as dguzek suggested.

Tested the build on Windows.

Apparently Windows 10 SDK doesn't work because winnt.h prevents compilation. I tested by using the Windows 8.1 SDK in Visual Studio Community 2019 and CMake 3.15.0 to create an x86 Build. I also needed to add "legacy_stdio_definitions.lib" under Properties->Linker->Input->Addition Dependencies for the StepMania build target.

**Comment by dguzek** [comment]
Thank you for this @teejusb.  It is my intention to wait a few more days to see if anyone else has feedback.  If there is no opposition by June 30, I'll merge then.

**Comment by dguzek** [comment]
Since there has been no feedback, I'll merge this now.  Thanks, wolfman2000 and @teejusb.

**Comment by shakesoda** [comment]
i apparently forgot to hit send on the reply i'd written up for this, but it has and had my +1

**Pull request merged**
