### PR TITLE
5.2: GtkModule: Add harfbuzz include path

### LINKED ISSUE #1850: GtkModules dependencies are missing harfbuzz include path
Building on Arch Linux with `WITH_GTK2=1` results in:
```bash
# [...]
Scanning dependencies of target GtkModule
[ 47%] Building CXX object src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-2.0/gdk/gdktypes.h:37,
                 from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/mkroening/.cache/yay/stepmania-git/src/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:8:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/GtkModule.dir/build.make:63: src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: src/CMakeFiles/GtkModule.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

This is because harfbuzz' include path is `/usr/include/harfbuzz/` on my system.

### PR DESCRIPTION
**Pull request by mwkroening**
Fixes #1850

I am not very experienced with CMake but this fixes the building issue on my system.

### CODE REVIEW

**Comment by mwkroening** [comment]
I don't think the CI failure is caused by this change.

It's failing to post something to IRC.

**Comment by mwkroening** [comment]
Should this target `master` or another branch like `5_1-new`?

**Comment by mwkroening** [comment]
Oops, those commits weren't ment to be on this branch.

**Comment by dguzek** [comment]
> Should this target master or another branch like 5_1-new?

The `master` branch is not currently supported and I don't know of any plans to change that.  I think it makes sense to target `5_1-new`.  

I don't know enough about cmake to comment on this pull request.

**Comment by mwkroening** [comment]
Thanks for your fast reply!

I'll rebase against `5_1-new` and test it this evening.

**Comment by Horsey-** [comment]
we should really change 5.1-new to master and send 5.2 off to its own Branch at this point....

**Comment by mwkroening** [comment]
I created another PR (#1852) for 5.1, as this should be in 5.2 as well, right?

**Comment by mkroening** [comment]
Closing this in favor of #1852.

**Pull request closed without merging**
