### PR TITLE
Remove no longer used ffmpeg bundle.

### PR DESCRIPTION
**Pull request by wolfman2000**
We get better versions via cmake/submodules anyway.

### CODE REVIEW

**Comment by gwaland** [comment]
I thought the submodules change in pull #792 was for the 5.1 branch not the master branch?

**Comment by wolfman2000** [comment]
5.1 uses submodules. master pulls it in during the first make step.

**Comment by gwaland** [comment]
Ahh. I did not know that.  that'd explain why I've been having video issues since cmake was introduced.  Thanks for the information. :)

**Comment by wolfman2000** [comment]
...wait. what video issues?

**Comment by gwaland** [comment]
the steps stutter on pump it up mk6 hardware on at least the 5.0.9 release when there's a background video.  After a lot of troubleshooting in http://www.stepmania.com/forums/general-stepmania/show/3914?start=8#post8659 I had minimized it but it was still present.  
I found this answer about pulling a new ffmpeg in cmake.  I reverted from my nightly build to 5.0.5 from source and the step stutter I've been fighting went away.

**Comment by wolfman2000** [comment]
It is entirely possible that we are using a poor version of ffmpeg here, or maybe bad configure parameters. What version of ffmpeg was used in 5.0.5 again, and what configure parameters are passed in?

**Comment by gwaland** [comment]
5.0.5 has 2.1.3 
My flags for 5.0.5 are:
./configure   --with-static-png   --with-static-jpeg --with-static-zlib  --with-static-bzip  --with-static-vorbis --prefix=/home/piu/sm5-install
My flags for 5.0.9 are: 
 cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=/home/piu/sm5-install .. && cmake  -DCMAKE_INSTALL_PREFIX=/home/piu/sm5-install

**Comment by wolfman2000** [comment]
@gwaland 5.0.9 also uses 2.1.3. I'll rephrase my question then.

What parameters are used when compiling/configuring the ffmpeg portion? Because to my knowledge, they should be the same. As far as the other configure flags you passed in, they don't affect ffmpeg to my knowledge, but it's still good to know.

**Comment by gwaland** [comment]
5.0.5 ffmpeg configuration line: 

 ./configure --shlibdir=/home/piu/sm5-install/stepmania-5.0 --enable-gpl --disable-programs --disable-doc --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter --disable-static --enable-shared

and based on ./Build/ffmpeg-prefix/src/ffmpeg-build/config.log 5.0.9 is using:

/home/piu/stepmania/extern/ffmpeg-linux-2.1.3/configure --disable-programs --disable-doc --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter --disable-shared --enable-static --enable-gpl --extra-cflags=-w

**Comment by wolfman2000** [comment]
Let's go over the ones I recognize.

`--enable-gpl`: Turn on for enabling GPL specific features. Both have it.
`--disable-programs`: Disable generating programs. Both have it.
`--disable-doc`: Disable generating documentation. Both have it.
`--disable-avdevice`: Disable using the avdevice features. Both have it.
`--disable-swresample`: Disable using the swresample features. Both have it.
`--disable-postproc`: Disable using the postproc features. Both have it.
`--disable-avfilter`: Disable using the avfilter features. Both have it.
`--disable-static`, `--enable-static`, `--disable-shared`, `--enable-shared`: Determine if we are building a static or shared library. 5.0.5 uses a shared library, 5.0.9 uses a static one. There's at least one key difference.
`--extra-cflags`: Additional flags to pass to ffmpeg. All `-w` does here is silence warnings, so it makes no difference during building.
`--shlibdir`: ...okay, you got me on this one. What IS that command for?

The issue is likely within either the static vs shared library or the lack of that shlib command. If I remember correctly, I recently merged in a branch that moved the ffmpeg setup to a separate cmake file. If `CMake/SetupFfmpeg.cmake` exists, go in there to find the cmake configuration. If it does not, it will be in `StepmaniaCore.cmake`. Adjust the flags there and tell me if behavior improves.

**Comment by gwaland** [comment]
After adjusting the flags in SetupFfmpeg.cmake and changing the linked file names in CMakeLists.txt I was able to get it running with shared instead of static.  Initial tests looked like a partial improvement but I'm going to do some actual side by side testing of the three versions(5.0.5, 5.0.9 unmodified, 5.0.9 shared ffmpeg) tonight.

**Comment by wolfman2000** [comment]
@gwaland I'm open to the idea that shared may work better. What do the cmake files look like with this change? Have you completed the side by side testing?

**Comment by gwaland** [comment]
After comparing the same song side by side I've determined that there is no exceptional difference between shared and static on ffmpeg.  I lean towards leaving it static as that saves with having to move shared objects around along with the binary. 

I did have the audio crash while I was playing and that smoothed out the playing completely in my testing.  So I'm off to another rabbit hole.  I don't think ffmpeg is the culprit at this point. 

Thank you for humoring me.

**Comment by kyzentun** [comment]
The only time I've personally had audio crashes was in Simply Love.  Never figured out why, but I was able to narrow it down to a couple specific audio files and avoid the crash by removing them.

**Comment by gwaland** [comment]
This was the first and only time I've had it crash.  I'm using the default theme for all my testing.

**Comment by wolfman2000** [comment]
@gwaland I'll ask for confirmation. Is this alright to merge?

**Comment by gwaland** [comment]
From my standpoint yes.

**Comment by wolfman2000** [comment]
Then consider it done.

**Pull request merged**
