### PR TITLE
Add kb9, make kb7 a bit more friendly

### PR DESCRIPTION
**Pull request by zetaPRIME**
kb9 is effectively an extended kb7, with a 7key style that uses kb7 charts as-is and a 9key that uses pnm_nine charts.

Changes to kb7 consist of giving the keys friendlier names to reflect the layout, and mapping the center key to Start, following kb9.

### CODE REVIEW

**Comment by shakesoda** [comment]
I feel like if kb9 has both modes, kb7 should just be removed in favor of kb9_7k

**Comment by sillybear** [comment]
I can finally make a Gitadora DrumMania theme with this.

**Comment by zetaPRIME** [comment]
...okay then, apparently testplaying a kb7 chart with gametype set to kb9 screws up the keymappings (it works fine in normal gameplay...)
suspect it's because it's not actually using the style it's assigned to

**Comment by Riev3Chan** [comment]
I think we should be able to tell the engine how many lanes we want. Instead of using per-game configs.

**Comment by shakesoda** [comment]
That's planned for SM6, this is how it works for 5.x though.

**Comment by thereallollolman** [comment]
Has SM6 even been planned though?

**Comment by Flameshadowxeroshin** [comment]
sm6 was planned and then cancelled, at least in its planned form

**Comment by Scraticus** [comment]
This is for 5.2 which has become abandoned, if you wish to resubmit for 5.1, please feel free!

**Pull request closed without merging**
