### PR TITLE
Fullscreen revamp 510

### LINKED ISSUE #224: Broken Fullscreen under OS X
When opening the current latest version in OS X (commit 6104c3f) and entering full screen, no picture is displayed. The game continues to run and accept input, with fully working sound, but the screen is black.

Returning to windowed mode fixes the issue.

Tested under OS X Mountain Lion 10.8.5 on a 2012 Macbook Air with Intel HD Graphics 4000.

### PR DESCRIPTION
**Pull request by drewbarbs**
Fullscreen Revamp
======================

This patch revamps the fullscreen implementation on Linux, expands the data structures used to represent available displays/display modes, and reworks the graphics settings menu to give more control over the display setting.

This PR is based on #497, but significantly expanded. It establishes the infrastructure required to give the user the choice of the display on which to go fullscreen (#176) and whether to go "fullscreen exclusive" or "fullscreen borderless-window" (#428). All this functionality is implemented for Linux (X11 backend), whereas the Windows and MacOS display settings are functionally unchanged. The plan is to get this merged, then individually address each of those platforms, for which the PRs will be smaller in scope.

`DisplayResolutions` to `DisplaySpecs`
---------------------------------------------
All supported platforms offer a way to query for the properties of the display devices attached to the machine: their supported modes, their current mode, their position in the global screen space, etc. In this PR, all this information is captured in the set of `DisplaySpecs`. A `DisplayMode` groups width, height, and refresh rate.

On Linux, the `DisplaySpecs` returned from `LowLevelWindow_X11` are fairly complete; the implementation uses XRandR 1.2 features (if available) to retrieve the list of outputs and constructs a `DisplaySpec` for each. The Windows and MacOS code has (for now) been "shimmed" to only return a set with a single display titled "Fullscreen" with the same resolutions as are currently being retrieved, presented in the options menu.

UI/Theme Change
-----------
Now that each display is grouped with the modes it supports, and each mode groups a resolution and a refresh rate, it seemed appropriate to modify the "Graphics/Sound Options" menu of the _fallback theme to

1. Give the option of which display to use for fullscreen (if the platform supports it), or to go windowed
2. Dynamically update the options for aspect ratio based on what resolutions the chosen display advertises (or give the standard list for Windowed mode)
3. Dynamically update the choices for Display Resolution based on the chosen Aspect Ratio
4. Dynamically update the choices for Refresh Rate based on choice of Display Resolution
5. Give the option for Fullscreen Type to be "Exclusive" or "Borderless Window" (if supported, otherwise just present a single "Default" option).

Presenting the display settings in this way allows only valid option combinations to be chosen, addressing #139.

In order to support the above UI change, the "Display Mode", "Aspect Ratio", "Display Resolution", and "Refresh Rate" option rows have been rewritten as Lua `OptionRowHandler`s in the `_fallback` theme. This required some expansion of the `OptionRowHandlerLua` class to allow a Lua option row to indicate the "effects" a choice has (e.g. resolution changed, Preferences.ini should be saved, etc.), and to allow it to dynamically change the list of choices based on received messages. The Luadoc has been updated accordingly.

Linux changes
-----------------
The `TryVideoMode` and `GetDisplaySpecs` (formerly `GetDisplayResolutions`) functions in `LowLevelWindow_X11.cpp` have been rewritten to query per-output information via `libXrandr`, and to (optionally) use `libXrandr` to configure per-output mode change and fullscreen, which _does not_ alter the configuration of the X screen. For more information on the use of `libXrandr`, see @roothorick 's excellent [post](https://www.reddit.com/r/gamedev/comments/2w8ahe/changing_resolutions_for_fullscreen_in_x11_linux/) on /r/gamedev.

Furthermore, support for borderless fullscreen windows is added, provided the user's window manager supports `_NET_WM_STATE_FULLSCREEN`. Non-window resolutions are implemented by rendering to a texture at the requested resolution, then rendering the texture to a full window-sized quad.

MacOS and Windows (lack of) changes
----------------------------------------
MacOS and Windows functionality should be effectively unchanged by this PR. In particular, this *does not* fix #224 (that's next on the list).

After some preliminary research, it seems it will be fairly straightforward to support both "exclusive" and "FSBW" fullscreen modes on Windows, on multiple monitors, as is done for Linux in this PR. For MacOS, many of the functions used to create a fullscreen OpenGL context and change display modes are deprecated/discouraged, so it seems the best option is to use `NSOpenGLView` to go fullscreen and change only the back-buffer size, as suggested by [this guide](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_fullscreen/opengl_cgl.html)

### CODE REVIEW

**Comment by wolfman2000** [comment]
I'm going to ask that if there are no issues with this branch, then please rebase the commits down to two commits. One commit should contain all of @roothorick's commits, and the other should contain all of yours.

**Comment by shakesoda** [comment]
definitely squash the commits into as few as possible.

**Comment by drewbarbs** [comment]
Ok, got it down to 10 I think roughly represent major milestones

**Comment by wolfman2000** [comment]
...well, better than the starting sixty or so.

**Pull request merged**
