### PR TITLE
Deprecated build files and DLLs cleanup.

### PR DESCRIPTION
**Pull request by Prcuvu**
Preventing people from running into deprecated build files after reading [this document](http://www.stepmania.com/wiki/compiling-stepmania/), which is surely outdated.

Removed some statically linked libraries' DLLs.
I'm not sure whether MSVC runtime DLLs should be removed, but it seems awkward to include all versions of them.

### CODE REVIEW

**Comment by wolfman2000** [comment]
I do appreciate the attempt, don't get me wrong. However, some of these items need to be looked at in more detail.

This is no guaranteed to be merged into master for some time.

**Comment by Prcuvu** [comment]
This PR will be closed for a cleanup.

**Comment by shakesoda** [comment]
stepmania does depend on zlib at runtime, as libpng depends on it and I think smzip decompression uses it as well.

**Comment by Prcuvu** [comment]
They do, but zlib and libpng were statically linked in Windows builds.

**Pull request closed without merging**
