### PR TITLE
give CryptManager and Lua access to tomcrypt's SHA256

### PR DESCRIPTION
**Pull request by quietly-turning**
# What

This adds libtomcrypt's SHA256 hash function to CryptManager with Lua hooks.  It follows along with the C++ patterns Glenn wrote a decade and a half ago for CryptMananger's MD5 and SHA1 functions.

StepMania's CMakeProject-tomcrypt file has been updated to build with *sha256* symbols.  Invoking cmake to build with system tomcrypt (e.g. `cmake -DWITH_SYSTEM_TOMCRYPT=ON`) works fine as-is.

The original SM functions for SHA1 and MD5 return binary formatted strings, so these new SHA256 functions follow suit.  This pull request also exposes RageUtil's existing `BinaryToHex` as a global Lua function to help themers who want a hash formatted in hex.

# Why

Existing SM5 themes (Simply Love, Digital Dance, Waterfall, etc.) use SHA256 hashes to generate QR codes for uploading scores to [GrooveStats](https://groovestats.com).

The current [pure-Lua implementation](https://github.com/quietly-turning/Simply-Love-SM5/blob/564bb7891e13aa8b536a092045c72d6624dfe0fb/Scripts/sha2for51.lua) works, but is slow.  Since the tomcrypt library already has SHA256 implemented, adding Lua hooks seemed like low-hanging fruit.

The faster the hash can be computed, the faster the QR code can be generated, allowing the Evaluation screen to be shown.

# Build Tests

Build tests are currently failing on Windows, but that seems unrelated to these changes.

# Performance

I used this Lua to do some rudimentary tests comparing the performance of the pure-Lua implementation with libtomcrypt's.

```lua
local songs = {
	-- 654 steps
	"Mute Sims X2/Lament Configuration",

	-- 4045 steps ("Is this hash really fast enough?")
	"Pendulum/Another Planet",

	-- 22897 steps
	"Cranked Pastry/Last Trip",

	-- 576000 steps 😭
	"Crapyard Scent/24 hours of 100 bpm stream"
}

for i,v in ipairs(songs) do
	local song = SONGMAN:FindSong(v)
	local steps = song:GetOneSteps("StepsType_Dance_Single", "Difficulty_Challenge" )
	
	-- ParseMsdFile and GetChartDataAndBpmForSM are specific to Simply Love
	local msdFile, _      = ParseMsdFile(steps)
	local chartDataAndBpm = GetChartDataAndBpmForSM(msdFile, "dance-single", "Challenge", steps:GetDescription())
	
	-- get uptime now, prior to hashing using SM engine
	local time_at_start = GetTimeSinceStart()
	-- get hash using CRYPTMAN, assess time
	local hash1 = BinaryToHex( CRYPTMAN:SHA256String(chartDataAndBpm) )
	local time1 = GetTimeSinceStart() - time_at_start
	
	-- get uptime again, prior to hashing using Lua
	time_at_start = GetTimeSinceStart()
	-- get hash using Lua, assess time
	local hash2 = sha256( chartDataAndBpm )
	local time2 = GetTimeSinceStart() - time_at_start

	-- print results to log.txt
	Trace( "-----------------------------------------" )
	Trace( v ) -- group/song name
	Trace( "CRYPTMAN hash: "..hash1)
	Trace( "     Lua hash: "..hash2)
	Trace( " hashes match: "..tostring(hash1==hash2))
	Trace( "CRYPTMAN time: "..("%f"):format(time1) )
	Trace( "     Lua time: "..("%f"):format(time2) )
end
```

Unsurprisingly, using libtomcrypt was substantially faster.
```
-----------------------------------------
Mute Sims X2/Lament Configuration
CRYPTMAN hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
     Lua hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 hashes match: true
CRYPTMAN time: 0.000014
     Lua time: 0.000441
-----------------------------------------
Pendulum/Another Planet
CRYPTMAN hash: eb38b776982f998eaef3dce1c457217c864c7c9694b5b863069126cfe714ee26
     Lua hash: eb38b776982f998eaef3dce1c457217c864c7c9694b5b863069126cfe714ee26
 hashes match: true
CRYPTMAN time: 0.000133
     Lua time: 0.101661
-----------------------------------------
Cranked Pastry/Last Trip
CRYPTMAN hash: 13b104ce4d7feefa280cfdb84d8ed6be3bd3e40ad0179c6ad35fa16c1cec6eae
     Lua hash: 13b104ce4d7feefa280cfdb84d8ed6be3bd3e40ad0179c6ad35fa16c1cec6eae
 hashes match: true
CRYPTMAN time: 0.000588
     Lua time: 0.510532
-----------------------------------------
Crapyard Scent/24 hours of 100 bpm stream
CRYPTMAN hash: 55ee40e5079ebf6cad9bd0f5c6391ce44f8e2e35ae518a584bebe0fbf1394dad
     Lua hash: 55ee40e5079ebf6cad9bd0f5c6391ce44f8e2e35ae518a584bebe0fbf1394dad
 hashes match: true
CRYPTMAN time: 0.014126
     Lua time: 11.573550
-----------------------------------------
```

### CODE REVIEW

**Comment by Scraticus** [comment]
I have reservations about allowing the crypt features to be accessed in Lua. 

This is an enhancement for everything based on your theme and it's derivatives/Simply Love clones, as no other theme is able/allowed to use the GrooveStats system at the moment.

I'll let the other SM Devs have their say, but this to me seems that anyone with lua knowledge could potentially mistreat the hashing system for Groovestats.

**Comment by quietly-turning** [comment]
Thanks for the feedback, @Scraticus!

Can you provide a concrete example/scenario illustrating your reservations?

**Comment by coderjo** [comment]
If someone wants to misuse the GrooveStats QR API, they can do it already with the same pure lua implementation that SL currently uses. This PR doesn't change that. All it does is make the hash generation faster.

**Comment by dinsfire64** [comment]
While the implementation and use of the hash is being used to identify charts with the service GrooveStats, this PR only allows LUA based themes to ask the engine to preform a hash for them.

If someone wants to abuse access to GrooveStats they could do so currently. There is no encryption or private/public key to associate machines with accounts to prevent tampering. It's currently an honor system.

By allowing the engine to preform the hash vs preforming the hash in lua makes no difference to how someone could currently abuse the GrooveStats system.

This PR is only allowing for the removal of the lua layer of the code and allowing the engine to compute a hash for the theme.

I have no issues with this PR and believe that "complicated math" for a known algorithm (especially one the engine already can preform) should be a task of the engine. The engine is compiled for the target system (or architecture) and can run code much faster than an interpretive sublayer (lua). 

The only reason for a lua implementation of this kind of math would be for a such a unique algorithm that isn't in a common library. Interpretatively that is an expensive job.

**Comment by geefr** [comment]
(What Din said) Code is a solid implementation too by the looks of it, and anything that makes the codebase cleaner/more consistent gets a +1 from me for what it's worth.

**Comment by RodentVienna** [comment]
On a sidenote. What are the mentioned digital dance or waterfall themes? Thank you

**Comment by Scraticus** [comment]
Ok, if everyone is fine with this, and opening up the QR/Hashing options to other non-simply love themes, I have no issues with this being merged. 

It will need testing for sure however, as I see the CI failed for windows.

**Comment by quietly-turning** [comment]
Thanks for the feedback, everyone.

I'm realizing I forgot to update the Lua Documentation here, so I'll add that to this pull request soon.

---

I agree that Windows build tests should be fixed, though as I noted, the linker errors seem to be unrelated to any changes here.  The last commit to `5_1-new` was 1c869edab5eba6d6975c137642cd64fef237eea9 on 5 July 2020, and the Windows linker errors started sometime between #2043 (28 July 2020, no Windows linker errors in CI) and #2048 (22 August 2020).

**Comment by coderjo** [comment]
I tracked the windows build issue down to #1947, but I don't have more time at the moment to look into why liblua and SM have different ideas of symbol names. (Perhaps there is a define that is needed while building lua to tell it to not do extern "C" around their code?)

ETA: created issue #2054 for this linking problem.

**Comment by coderjo** [comment]
This PR builds fine on windows, once the linker issue is corrected. I didn't have an easy means to test it works properly, though.

**Comment by quietly-turning** [comment]
Thanks, @coderjo!

I did update this pull request to include relevant changes to the LuaDocs (and subsequently went down a git force push CLI rabbit hole for about an hour).

I then rebuilt SM and reran my Lua performance test (from this thread's original post).  There were no Lua errors, the hashes match, using the engine to do the hashing is still multiple orders of magnitude faster, and with #2055 in place, CI is passing again.  

Thanks for the discussion, everyone. 🙂

**Pull request merged**
