### PR TITLE
Persistent Coins

### PR DESCRIPTION
**Pull request by concubidated**
On Coins Insert a file Save/Coin.ini is created, if it does
not exist, which stores the number of coins currrently in
m_iCoins. Whenever m_iCoins is update, the Coin.ini is updated.

On boot, Coin.ini is read and m_iCoins is set to that value.

resolves: #1403

### CODE REVIEW

**Comment by kyzentun** [comment]
Test whether the coins value is saved correctly when AutoSetStyle is turned on and double premium is off and the player switches from single to double.

That might lead to this part that also sets the coins value being used:
https://github.com/stepmania/stepmania/blob/5_1-new/src/GameState.cpp#L513

**Comment by concubidated** [comment]
With AutoSetStyle, and Double Premium off, the coin counter is not marked down. When a 2nd player joins and Joint Premium off, the coin counter does get marked down and is working correctly.

I also tested corrupting the Coin.ini file and on boot we get 0 credits and on Insert Credit we get a fixed file.

**Comment by concubidated** [comment]
Anything else, that would need testing?

**Comment by concubidated** [comment]
Tested making the file read only. No issues
Tested increasing the file manually past MAX_NUM_CREDITS, and the value in the file and in game gets reset to zero.

**Comment by shakesoda** [comment]
👍

**Pull request merged**
