### PR TITLE
Use libXtst again with CMake

### PR DESCRIPTION
**Pull request by eliask**
It seems that Xtst was never used after the transition to CMake.

This is related to #1902

### CODE REVIEW

**Comment by quietly-turning** [comment]
Thanks for this, @eliask!

I can't comment on the changes here, but did want to ask if you'd intended to have this merged with `master`.  The project's default branch has been `5_1-new` since #1873.

**Comment by eliask** [comment]
Ah, I hadn't noticed that `5_1-new` was the default branch.
I adapted this to the default branch now:)

**Comment by shakesoda** [comment]
looks like this is conflicting with one of the previous PR's, can you update it?

**Comment by eliask** [comment]
Looks like the CI is passing now. I rebased this on top of the present `5_1-new`.

**Comment by shakesoda** [comment]
thanks 👍

**Pull request merged**
