### PR TITLE
Course mode trail generation fixes

### LINKED ISSUE #1828: Course file: Wildcard entry overwrites rest of course; bizarre group-wildcard behavior
I noticed this while working on a feature for #1821 in my own fork. I went back to master for a bit and cleaned/built to confirm the issue isn't in my code. Take this example course file:

```
#COURSE:RANDOM GARBAGE!;
#BANNER:ChallengingRandom5.png;
#BACKGROUND:ChallengingRandom5-bg.png;
#SCRIPTER:the ghost of christmas past;

#SONG:Goin' Under:HEAVY:;
#SONG:*:MEDIUM:;
#SONG:MechaTribe Assault:HEAVY:;
#SONG:Springtime:HEAVY:;
#SONG:*:LIGHT:;
#SONG:Goin' Under:HEAVY:;
#SONG:Springtime:HEAVY:;
```

When you load this thing ingame, the resulting course will act as if the original .crs file was:

```
#SONG:Goin' Under:HEAVY:;
#SONG:*:MEDIUM:;
#SONG:*:MEDIUM:;
#SONG:*:MEDIUM:;
#SONG:*:LIGHT:;
#SONG:*:LIGHT:;
#SONG:*:LIGHT:;
```

So it looks like any defined `#SONG` using a wildcard causes all `#SONG`s thereafter to use the same parameters, with new wildcards overwriting the old. This is easy to confirm, as the difficulty pattern for the course ingame will be orange-yellow-yellow-yellow-green-green-green rather than the expected orange-yellow-orange-orange-green-orange-orange. (And obviously, the songs themselves past the first will be random, rather than as specified.)

Group wildcards also have really _really_ bizarre behaviors. With this file:

```
#COURSE:RANDOM GARBAGE (with groups)!;
#BANNER:ChallengingRandom5.png;
#BACKGROUND:ChallengingRandom5-bg.png;
#SCRIPTER:program's not workin, call the cops;

#SONG:Goin' Under:HEAVY:;
#SONG:StepMania 5/*:MEDIUM:;
#SONG:MechaTribe Assault:HEAVY:;
#SONG:Springtime:HEAVY:;
#SONG:StepMania 5/*:LIGHT:;
#SONG:Goin' Under:HEAVY:;
#SONG:Springtime:HEAVY:;
```

It _might_ work as expected on first view from the course wheel. If you then back out to the main menu and go _back_, the course will change significantly and in ways that make very little sense. And it doesn't seem to be consistent as to what exactly happens: every time you bounce out to the main menu and go back to the course wheel, the exact effect changes. The course may say it has 7 songs in the header but only present 6 in the course preview on the left; one of the group wildcarded `#SONG`s may be missing but will have the bizarre overwrite effect for the next couple songs... I'm really not sure what the deal is. 

Unfortunately I'm not seeing anything in the userlog pertaining to this. From what I can tell, it doesn't seem to be a parsing issue or anything; in my own fork, I've dumped the individual `CourseEntry`s in the course after [this line immediately before trail generation](https://github.com/stepmania/stepmania/blob/b95e49216eb2974b8e0f69b6603595df1c698ccd/src/Course.cpp#L459) and all of those were intact. Given the group wildcard behavior changing on going back to the title screen (which coincides with when the RNG seed gets changed between rounds, I think?), I'm thinking it could be an issue somewhere in trail generation. I'll probably take a crack at figuring out where this is going wrong on another branch.

(I might've overlooked something in the CRS, but replacing the wildcards makes everything work as expected, so I'm inclined to call it a bug)

### PR DESCRIPTION
**Pull request by jalbert-dev**
Fix #1828 

This implements fixes for trail generation bugs noted in that issue, both in nonstop/oni and endless mode. In particular:

- Wildcards and group wildcards now work properly and don't infect the following course entries
- Endless course generation would crash in `GetAllMatchingEndless` when no steps existed for a song in a certain gamemode (attempting to obtain `begin()` of size-0 vector)
- Endless course generation algorithm was screwed up, so I tore it out and stuck a new one in
- Endless courses were not allowed to have individual tracks differing in difficulty from the course itself, for some reason (so Easy courses could only have Easy charts selected, etc.) I don't know if there's a good rationale for this (EDIT: PR #1022 partially explains it) but I noticed nonstop courses do not have this behavior so I removed it from the endless coursegen

(At this point I'm not sure _why_ it is that endless and nonstop use different course generation functions; they appear to be 90% similar, and I have a feeling most of the above bugs are because one codepath got fixes and the other didn't. I'm pretty new to the codebase though so I left it as is.)

I decided to remove the previous algorithm used by `GetTrailUnsortedEndless` to pick songs and steps from course entries because it wasn't clear what it was supposed to be doing outside of some comments left way back at the time of commit (PR #1002), and more importantly, didn't _work_. (Not sure how long this has been in a broken state.) I'm not sure my implementation here works 100% the way the original author intended, but it's basically this:

For each course entry:
1. Get all songs/steps according to song/step criteria (as normal)
2. If generating from a * (random sort):
2a. Filter out any song/step pairs with songs that have already been selected during trail generation; if no candidates left, go to 2b., else 3.
2b. Filter out the last played song; if no candidates left, give up trying to filter (should only happen if a wildcard has only one possible matching song)
3. Sort songs by course entry sort setting, then choose the appropriate song and random matching chart
4. Update already-selected list and last-played

This (fairly naive) algorithm acts as a pseudo-shuffle in that the only time repeats are possible is when all songs that can be generated from a given course entry are in the pool. However, the algorithm falls back to randomness (though it doesn't allow for selecting the same song twice) at that point, since there's no point at which the already-selected vector is cleared. If every course entry were identical it would be a different story, but since every entry has a different pool of allowed songs it isn't clear where would be the correct time to reset the shuffle. (Maybe could do a loop over course entries to get the superset of all possible songs and use the size of that to determine when to reset the already-selected pool?)

This implementation doesn't forbid repeat songs in cases such as:

```
#SONG:*:HEAVY;
#SONG:Springtime:HEAVY;
```

Could use one-song lookahead with wildcards to get around this, but I opted to leave it alone for now.

My implementation is pretty brute-force in terms of time complexity, so there's definitely room for improvement (and I'd be happy to hear any feedback as to how to improve this). I did some profiling of a release build in VS and it seems like the majority of CPU time spent is in `GetAllMatchingEndless`, so I didn't put much into optimizing the algorithm itself. It may be a different story on lower-spec hardware;  I don't have any on-hand. I used a stress-test course with a couple hundred wildcard-selected songs chosen from a pretty sizeable song pool and it loaded quickly enough on my laptop.

Tried to more-or-less match existing code style, dunno how well I succeeded.

**EDIT:** If anyone has repro information for #1020, I'd appreciate it. I'd like to make sure this isn't introducing a regression. Did some testing (removed a Medium chart and used it at the start of an Endless course, etc.) and I don't see any problems but a specific known problematic case might make that a bit easier to tell.

### CODE REVIEW

**Comment by dguzek** [comment]
This is fantastic!  Thank you so much for not only working on this but providing such a detailed and well-organized pull request write-up.

I'm going pull these commits into my local `5_1-new` branch later today to test and then report back.  I anticipate they'll get merged into `master` (as you requested) but also `5_1-new` which is presently the more active and used branch.

Again, thanks! 

---

It's great for me, especially, that you tackled some Course-related stuff.  I've wanted to add an "Endless Mode" to the Simply Love theme in the spirit of encouraging fitness for at-home players for a long time now.  

The various quirks and bugs that you're finding and describing made me believe I was going to have to do this 100% theme-side because I just don't know enough C++ to fix the engine.  I was laying the groundwork for creating, sorting, and filtering theme-side data structures to generate "Courses" within specified parameters on the fly.   I had ideas about offering players the ability to save those "Courses" to disk if they especially liked what they'd played that session.

I had a lot of ideas, and was willing to try to do it theme-side, but knew the engine was the right way to do it.  So if any of that sounds interesting and worthwhile to you, maybe this could be the start of something?

**Comment by jalbert-dev** [comment]
Thanks for testing! I wasn't sure which branch was the active development branch, so I ended up going with where I saw most open PRs pointing at, which was `master`. (Didn't see a contribution guide or anything like that)

I _was_ working on #1821 along the lines of what I mentioned in that issue, and I had things working pretty well in nonstop/oni before I ran into these endless mode problems, so that might interest you. Further work on that is sorta dependent on this PR though so that I can test it.

If you have any ideas for other stuff or notice any incorrect behavior when testing, feel free to point it out. Thanks again!

**Comment by dguzek** [comment]
Just checking in to say I haven't forgotten about this!  My free mental cycles have been occupied elsewhere recently, but I'm going to make an effort to test this PR this weekend.

**Comment by eliask** [comment]
Bump.

I encountered a crash on `5_1-new` today that's probably solved by this pull request.

On `5_1-new` on endless mode, the following problem can occur. `vpSongs` can have size 0, yet the following line gets executed:
```
resolved.pSong = vpSongs[ songIndex ];
```

See: https://github.com/stepmania/stepmania/blob/5_1-new/src/Course.cpp#L723

**Comment by blindbox** [comment]
It has been 4 years so my memory might be iffy. I was pretty unskilled back then, too.

@eliask Indeed, vpSongs can be empty and the iteration should have been `continued`.

@jalbert-dev The new codepath was because I didn't understand how the other modes work (and I still don't). If I remembered correctly, this was what I ~~noticed from observation (not from reading the code itself, however), so this may be incorrect.~~ noticed from reading the code (my memory came back), which may not be correct.

* at each iteration, it will randomize the song list it was initially given.
* Then from this new, randomized list, add one that fits the requirement to the trail entries.

So my changes made this happen instead (along the bugs it introduced).

* Randomize the song list only once.
* From the song list that was randomized, add all to the trail entry if it fits the requirement.

Looking back at my code though, it's pretty crap, like:

* Why didn't I just move the sort to outside of the for loop?
* Why did #1022 re-declare `vpSongs` and friend in the wrong scope, when the original pr in #1002 didn't.
* GetTrailsUnsortedEndless should be renamed as AddTrailEntriesEndless because that's what it's actually doing.

Hope this helps.

**Comment by quietly-turning** [comment]
Hey @jalbert-dev, I apologize for letting this sit for the last year.  If it's okay, I'd like to get the work you did here out of Endless Limbo and merged with the `5_1-new` branch.

I `cherry-pick`ed  these locally into `5_1-new`, changed line 780 of Course.cpp from

```cpp
 resolved.pSteps = songSteps[random_up_to(rnd, songSteps.size())]; 
```

to

```cpp
resolved.pSteps = songSteps[RandomInt(songSteps.size())];
```

and it seems to work as advertised. 🙂

Would you be okay with me closing this PR and opening a new one with your 4 commits plus 1 from me changing the use of `random_up_to`?

**Comment by jalbert-dev** [comment]
I'm a bit late getting back to you (sorry about that), but that's totally fine with me! Thanks for taking care of it.

**Comment by quietly-turning** [comment]
Closing this, as it's been effectively replaced by #2009.  Thanks for doing the work, @jalbert-dev!

**Pull request closed without merging**
