### PR TITLE
New quants, to experiment with/test out the new noteskin system

### PR DESCRIPTION
**Pull request by 1033Forest**
These can be used to test out the noteskin system not being limited to 192nd quantization, and to test noteskins with an x16 graphic (such as zenbuquan). These can be turned on or off in the operator menu (default off). I know that none of these notes (except maybe 96th and 192nd) are useful in any stepchart whatsoever, these notes are only for experimenting. Use at your own risk.

These will only be for 5.1, and not 5.0.

### CODE REVIEW

**Comment by kyzentun** [comment]
We're not adding any quantizations beyond 192nd.  Extending a shortsighted solution does not make it better.  The way notes are quantized in the note data needs to be changed to have a general solution.

**Comment by 1033Forest** [comment]
Can I add these to my own personal fork of SM, just to experiment with them? That way only I can use them

**Comment by wolfman2000** [comment]
@1033Forest Adding code to your own fork is completely allowed. Just know that if any file changes take place, you are responsible for reconciling the differences. (Feel free to ask for some assistance if you get stuck, but it's ultimately up to you.)

I am aware of the `#ROWSPERBEAT` flag. It's not something we want to support at this time beyond the fixed 48.

**Comment by 1033Forest** [comment]
If I want to test out the mine holds, will just removing the 2 slashes at the beginning of the code for them work?

**Comment by 1033Forest** [comment]
I will try adding 128th note support. But that means I have to make it support 384ths too.

If I try them on my fork of 5.1, and they work, I'm sending in a PR. How do I create a new branch?

**Comment by 1033Forest** [comment]
The only quantization beyond 192nd I want to add is 384th (even though they are useless, they are just to make 128ths work properly). I need to figure out how to create a new, fresh 5_1_0 branch.

128th can be used in 4x slowdowns (played as if they were 32nds). Decided to add this as it is the note between 96th and 192nd. 128ths are actually real notes that have been used in some musical scores: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/1-128th_note.svg/2000px-1-128th_note.svg.png

384th, no good use for them... (can be used to switch up color in KB files, or just for experimenting)

When I finish adding them, these will be the supported notes so far:
4th
8th
12th (4th triplet)
16th
24th (8th triplet)
32nd
48th (16th triplet)
64th
96th (32nd triplet) (NEW)
128th (NEW)
192nd (64th triplet)
384th (128th triplet) (NEW)

If I test them out, and they work, I'll wait until some other user-made features (like guitar mode) get PR'd into here before I PR the new quants.

**Pull request closed without merging**
