### PR TITLE
Actor frame texture

### PR DESCRIPTION
**Pull request by sigatrev**
I feel like a lot of people do not understand what these things do but I am overly in love with them so I thought I'd fix a few bugs and give you some examples.

### CODE REVIEW

**Comment by dguzek** [comment]
:+1:

**Comment by freem** [comment]
+1 for this as well (at least for the examples; haven't had a chance to test the code yet, but I am assuming it works for now)

**Comment by shakesoda** [comment]
Looks solid to me, merged. Thanks!

**Comment by SpoOkyMagician** [comment]
I have yet to try those yet. I will probably read the example over later though. Thanks. :)

**Pull request merged**
