### PR TITLE
Use batch syntax for commenting CI IRC postings.

### PR DESCRIPTION
**Pull request by mkroening**
This should fix the AppVeyor issue.

### CODE REVIEW

**Comment by mkroening** [comment]
Indeed it does. Please merge!

**Comment by quietly-turning** [comment]
Just to clarify, what is "the AppVeyor issue"?

**Comment by mkroening** [comment]
Ah, sorry. The recent appveyor builds fail because the IRC reporting was disabled via bash-style comments. As the relevant section is a batch script, the comment is interpreted as command and fails. This changes the comment style from bash-style to batch-style.

See: https://ci.appveyor.com/project/Nickito12/stepmania/builds/26594183

**Comment by quietly-turning** [comment]
Thank you for explaining the issue, the way it manifested, and your fix!  And thank you for all your recent pull requests!

**Pull request merged**
