### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by pixeldesu**
**Don't merge this yet, this is still in progress. Just opened for reviewing!**

Realizing some parts of the documentation haven't been touched for years a lot of clutter has assembled and I'm trying to clean up most of this. 

I'm not too much into the SM codebase, so I don't know what specific parts are absolutely unnecessary by now, which I also need a core maintainer for checking through the current state, so I can clean up the files and move them to Markdown formatting.

**Checklist:**

* [x] Clean up folder structure and sorting of files.
* [ ] Clean up files in general and move documentation-heavy files to Markdown.

### CODE REVIEW

**Comment by kyzentun** [comment]
The parts from AJ that talk about SM4 bother me.  Those need to be reviewed *very* carefully to make sure they're true for SM5.  I don't really have time to do an in-depth review until next week, and I can't think of anyone else that knows the theme system as thoroughly as I do.

**Comment by pixeldesu** [comment]
Take your time, there's no hurry with the documentation.

And maybe some other contributor might just turn up and answer stuff, who knows. I did the first steps by now and will continue once the reviewing is done!

**Comment by kyzentun** [comment]
Read some of it, does not look like something to merge.

# Docs/Developing/Messages.txt:
There needs to be a section at the beginning describing how to read the information in it.  As is, it's not clear what each section means.

Many (or all) of the things in this file aren't messages at all, they're commands that are executed on actors.  A message is something that is broadcast everywhere.  A command only affects an ActorFrame and its children.

GhostArrowRow is going away in 5.1.  The ColumnJudgment command doesn't belong in a general messages document anyway because it's something the noteskin does, so it belongs with other noteskin documentation.  5.1's noteskin system is documented in the default noteskin.

The section for GameState is formatted completely differently from the other sections.

The Set command for MusicWheelItem has other parameters besides the ones listed:  https://github.com/stepmania/stepmania/blob/master/src/MusicWheelItem.cpp#L291-L300




# aj's guide to shit.txt:
aj's guide to shit probably doesn't belong in SM5 docs at all.  It was written in 2007, targeting Stepmania 4.  90% of it is probably obsolete and will just mislead people making themes for Stepmania 5.

Skimming through, it looks very unfinished, as if it's just a quick placeholder.  LoadFont is definitely obsolete, Def.BitmapText has a Font field that can be used conveniently.




# readit.txt:
This seems to be a description of various experimental themes that don't exist anymore.  Not useful documentation of anything except history.



# Mods.txt:
This is a poorly reformatted snip from PlayerOptions.cpp.  It gives no explanation of any mods.  It's just a list of names, all of which can be found in the PlayerOptions section of Lua.xml.



# Other stuff:

PrepareScreens.txt, ScreenMessages.txt, and Screens.txt are borderline useful.

Screens.txt might give people the wrong impression, since many of those screens are unused, unmaintained, or unfinished in the engine.  A theme that wants the special features those screens were meant for (like a workout mode) would be better off creating a completely custom screen and not using the engine screen at all.

**Comment by freem** [comment]
just remove everything I've written because it's not up to your standards

**Pull request closed without merging**
