### PR TITLE
5_1-new: Fix building with clang/clang++

### LINKED ISSUE #1865: 5_1-new not buildable using clang/clang++
Trying to build using clang/clang++ like this
```bash
cmake \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    ..
```
fails on numerous errors.

Those errors must be fixed to be able to use the leak sanitizer in #1854.

### PR DESCRIPTION
**Pull request by mkroening**
Fixes #1865.

Depends on #1852.

This is a WIP, so I can work out the necessary CI changes.

### CODE REVIEW

**Comment by mkroening** [comment]
This fails because of #1867.

Aside from that and #1852, this is ready for review.

**Comment by mkroening** [comment]
Removed dependency on #1852 (see https://github.com/stepmania/stepmania/issues/1850#issuecomment-520180473) and rebased on latest upstream. This should now succeed all CI and is ready for review.

**Comment by mkroening** [comment]
Okay, @dguzek, let's start with this one. Currently StepMania does not compile using LLVM's [clang](https://clang.llvm.org/) (with or without LLVM's [libc++](https://libcxx.llvm.org/)). Clang and libc++ are popular alternatives to the GCC on Linux and clang is the default compiler on macOS.

We are even testing PRs against clang and libc++ but apparently did not catch that regression. See that CI is currently [failing](https://travis-ci.org/stepmania/stepmania/builds/570303139) on `5_1-new` but [succeeding](https://travis-ci.org/stepmania/stepmania/builds/570315355) with this PR.

Regarding the changes themselves: The first two commits are from the current master branch if I remember correctly. Please read the commit messages as well!

The first one adds the ["ctime" C++ Standard library header](https://en.cppreference.com/w/cpp/header/ctime). This is only working with other standard libraries because of other standard library headers importing "ctime", which are implemention details and should not be relied on anyways. Additionally this adds libc++ to be installed in the CI environments and verifies jsoncpp using the correct standard library.

The second one fixes clang needing this specific exception specification.

The third one is made by myself and circumvents a problem with compiling code depending on the low level support for a standard C++ library when multiple standard libraries are available (see [Travis CI](https://travis-ci.org/stepmania/stepmania/jobs/570175860#L2361)). I replaced the code relying on "cxxabi.h" with standard complying code. Note that in the new implementation we can't always get a name of the thrown variable. We only print specific information if a subclass of `std::exception` is catched. On the other hand to throw something that is not subclassing `std::exception` is very bad practice anyways.

What do you think? I'm not sure how comfortable you are with C++, so feel free to ask for more details!

**Comment by quietly-turning** [comment]
Thank you for taking the time to write all this, @mwkroening, and for working on all the pull requests you have lately.  I am sorry I've been absent/silent in responding here.

Reviewing your description of this pull request, I am confident that I am not qualified to merge the commits involved.  I'm completely out of my league here and feel it is prudent for me to be honest about that.

I am sorry about this.  I'm not sure what else to recommend at this time.

**Comment by shakesoda** [comment]
looks good to me, thanks 👍

**Comment by quietly-turning** [comment]
Thanks, shake.

**Pull request merged**
