### PR TITLE
An attempt to update StdString.h.

### PR DESCRIPTION
**Pull request by Prcuvu**
This is an attempt to update `StdString.h` to its [latest version] (http://www.codeproject.com/Articles/1146/CString-clone-Using-Standard-C). Some identifiers are renamed to avoid collisions with their namesakes defined in Windows headers.

Working on Visual Studio 2013 without errors found temporarily, *not* working on Visual Studio 2015 (generating "@* (* is a random character)" errors on program startup).
However, master branch does not work with Visual Studio 2015, either. Those problems can be submitted a separate issue.

Needs testing on non-Windows platforms. Feedback is welcome.

### CODE REVIEW

**Comment by wolfman2000** [comment]
For the record, I just built master on VS2015 without this PR. I got it to build, link, and run. There is a separate running issue that is not present in `5_1_0`, but that's for another time.

Why do you claim VS2015 does not work on master?

**Comment by Prcuvu** [comment]
Because my build with master and VS2015 does not read songs and profiles in user directory.

**Comment by Prcuvu** [comment]
Wow, Travis fails hard. Numeral minor fixes are predicted.

**Comment by wolfman2000** [comment]
@Prcuvu That is one of the things I've encountered between `master` and `5_1_0`. I have not identified why `5_1_0` works with that and `master` does not. That's for another day, however.

Likewise, some efforts have been put in to reduce reliance on StdString.h. It's not completely there, however.

As such, I need heavy convincing to allow this PR to be merged in.

**Comment by wolfman2000** [comment]
I'm heavily going to advise you re-address this one portion at a time. Don't replace all at once. It will only lead to disaster. Trust me: I know.

**Comment by Prcuvu** [comment]
Alright. I will replace this PR once I've done.

**Comment by Prcuvu** [comment]
A new library (`cppformat`) is being applied on `5_1_0` branch to replace `CStdString`, which is no longer being maintained. This PR shall be closed after 5.1.0 release.

**Comment by wolfman2000** [comment]
Half true @Prcuvu. `cppformat` helps more with replacing our custom printf style functions. `CStdString` is going to be replaced with `std::string`.

**Comment by wolfman2000** [comment]
Closed by #952.

**Pull request closed without merging**
