### PR TITLE
Update Background.cpp

### PR DESCRIPTION
**Pull request by sillybear**
Start RandomMovies immediately during gameplay rather than during first note.

### CODE REVIEW

**Comment by wolfman2000** [comment]
I'm unsure of the point of this one to be honest. Wouldn't it work better as a metric?

**Comment by sillybear** [comment]
That would be better. Care to update to apply your suggestion?

**Comment by kyzentun** [comment]
sillybear's code probably resulted in every random bg change that was generated having the same start beat, which would make the game change every frame until it hit the end of the list.  So I made sure that didn't happen and added a couple other metrics too.

https://github.com/stepmania/stepmania/commit/f1f1bd5ca69f5000a71404982a0bb693d5f9533b

**Comment by sillybear** [comment]
It is only applied in just the RandomMovies, not the BG Changes stated in any sm/ssc files, fyi. I've been using it for months in my own. And lately, there is one that request this feature somewhere, I decided to request it, but still, nvm.

**Pull request closed without merging**
