### PR TITLE
Split Chinese language into two different locales based on Simplified or Traditional script

### PR DESCRIPTION
**Pull request by Prcuvu**
Simplified Chinese and Traditional Chinese differ not only on glyphs used, but also on contemporary vocabularies. Currently this language is localized as the locale used in Taiwan, which is of Traditional Chinese script.

Changes have been made to `ArchHooks::GetPreferredLanguage()` and LanguageInfo bindings in `RageUtil.cpp`. `zh.ini` language files are renamed to `zh-Hant.ini`.

Tested on all three platforms, preferred language detection is working properly.

### CODE REVIEW

**Comment by Prcuvu** [comment]
@shakesoda Maybe you can find someone eligible for reviewing this localization-related PR?

**Comment by quietly-turning** [comment]
Thanks for your work on this, @Prcuvu!  

The changes to code seem fairly straightforward, and though I am not familiar with Simplified vs. Traditional Chinese (glyphs, vocabularies, anything), I trust that you are.  If no one else has feedback on this pull request in the next few days, I'll merge it.

---

Related: one of my current projects with the Simply Love theme is to incorporate @fishynuke's translation efforts (https://github.com/fishynuke/Simply-Love-SM5-ChineseVersion) into the main Simply Love repository at https://github.com/quietly-turning/Simply-Love-SM5.

If your work here in #1958 is merged, it seems I will start by renaming [zh.ini](https://github.com/fishynuke/Simply-Love-SM5-ChineseVersion/blob/master/Languages/zh.ini) to `zh-Hant.ini`.  Is that correct?

Again, thank you!

**Comment by Prcuvu** [comment]
@quietly-turning I just took a look at the Simply Love translation, it is using Traditional script. Does indeed have to become `zh-Hant.ini` after the merge.

**Comment by quietly-turning** [comment]
Thanks for this for pull request, @Prcuvu, and for your many contributions over time.

**Pull request merged**
