### PR TITLE
Another Amend, with a serious proposal

### PR DESCRIPTION
**Pull request by Andy8254**
The reason I'm doing this pull requests is to propose the devleopers to accept pull request #1224 (Updated Korean Glyphs) at your earliest convenience in order to show the Korean Translation properly at Stepmania. I want to stress out fact that the current version of Stepmania fails to show almost every character that are included in this file - which also denotes that ko.ini in _fallback and default are in no use - , since the Korean letters provided here cover only 2~3% of the 11,172 letters of the Korean Alphabet(Hangul.)

For more information, please read the issue #1222 stated by author of the pull request #1224 .

### CODE REVIEW

**Comment by Andy8254** [comment]
>

**Comment by Andy8254** [comment]
Oops, I accidentally closed the Pull request... 😅

**Comment by Andy8254** [comment]
Here's the link for the fonts I mentioned at #1804 

TTF for Windows:
http://appdown.naver.com/naver/font/NanumFont/setup/NanumFontSetup_TTF_ALL_hangeulcamp.exe

OTF for Mac:
http://appdown.naver.com/naver/font/NanumFont/setup/NanumFont_MacOS_OTF_ALL_hangeulcamp.dmg

**Comment by RyTak** [comment]
Clean up the errors with the Travis Cl build please :)

**Comment by shakesoda** [comment]
travis issue has nothing to do with this pr

**Comment by RyTak** [comment]
oh, my bad. just saw that it was a global issue

**Comment by Scraticus** [comment]
This is for 5.2 which is abandoned

**Pull request closed without merging**
