### PR TITLE
Add nine panel mode

### PR DESCRIPTION
**Pull request by aeubanks**

### CODE REVIEW

**Comment by Flameshadowxeroshin** [comment]
Why is this a new game?

**Comment by aeubanks** [comment]
How else would you recommend adding a 9 panel mode?

All the existing game modes are based off real games. There currently isn't an official 9 panel game (although there will be one soon), so I didn't want to put it as another type in another game mode.

**Comment by Flameshadowxeroshin** [comment]
techno already has double8, which doesn't exist in real technomotion. (for that matter, dance-routine doesn't exist in any released dance game.)

**Comment by shakesoda** [comment]
I'm not entirely opposed to merging this, but we really just need custom game types...

**Comment by aeubanks** [comment]
That would take a while, can we merge this in the meantime?

Also, how would you design/implement custom game types? I'm still not too familiar with stepmania codebase, but I might consider it as a future project.

**Pull request closed without merging**
