### PR TITLE
Add back SM4 CVS default noteskins

### PR DESCRIPTION
**Pull request by 1033Forest**
For SM4 players transitioning to SM5 who don't like the default gamma noteskin. (even though the animation is faster in SM5 than it is in SM4)

Since the 96th pull request got closed, there's no need to merge in the 96th source code. Just all I wanted to do was upload some files.

### CODE REVIEW

**Comment by kyzentun** [comment]
I'm against adding more SM5 noteskins.  Anything new should be made for SM5.1.

**Comment by 1033Forest** [comment]
Oh...

I am trying to figure out how to port these ancient SM4 noteskins to SM 5.1. I will ask someone who knows a lot about noteskins to help me. These SM4 noteskins still work on SM 5.0, only difference is the animation is faster and goes with the beat, and not slow like SM4's noteskins used to be. I am also planning to create graphics for new hold types that will be implemented soon (checkpoint holds, timed-release holds).

**Comment by kyzentun** [comment]
I also want to point out that default already packages too many noteskins.  There are several themers that have written custom noteskin options to allow hiding the noteskins that come with the game.

**Comment by shakesoda** [comment]
we've already got way too many skins included, just post the skins on the forums or something.

also, this PR includes your previous PR.

**Comment by 1033Forest** [comment]
How do I remove a previous PR?

**Comment by shakesoda** [comment]
you should do PRs from new branches.

**Pull request closed without merging**
