### PR TITLE
Build all external libraries on Windows.

### PR DESCRIPTION
**Pull request by Prcuvu**
These commits move libtommath and libtomcrypt to extern directory, update all bundled libraries (with StepMania customizations applied) and adjust dependencies to make sure all external libraries (except ffmpeg) are built from source and statically linked on Windows, then StepMania can be built with /MT flag.

Tested on Visual Studio 2013 and Debian Jessie.

### CODE REVIEW

**Comment by wolfman2000** [comment]
I see someone has tried to go ahead of schedule here. Not that that's a bad thing. ;)

However, this PR is doing too much too soon.

* autoconf/automake is not being removed yet due to concerns of MinGW compatibility. I've had some issues with getting that to work. Plus, #757 is making me think at least one option is missing still.
* I'll admit that being able to support both DirectX 9 and DirectX 10 (I'm presuming 10 due to dxerr.h being mentioned) may be a good thing. However, the idea is that cmake is used for compilation from here out. Cmake works for compiling under Visual Studio 2013. Technically, all visual studio projects are deprecated as well.
* libtommath and libtomcrypt are already moved to extern on the 5.1 branch.
* Why the version upgrades? I get that bug fixes may be a valid reason here, but what of the other non Windows builds? What versions do they use if they use the system equivalents?
* Too many commits are in here for a clean review. Rebasing would be advised.

I will advise that this request is split up into multiple requests. Do a single thing at a time, test, bring that specific thing in as a PR.

**Comment by wolfman2000** [comment]
...oh yeah. What StepMania customizations were applied where?

**Comment by Prcuvu** [comment]
* I've noticed #757 and restored autoconf/automake files in my latest commit.
* I've already removed all deprecated Visual Studio projects except smpackage and Texture Font Generator (I was not sure whether they were still in use, and both fails to build).
* Seems that I've done some duplication of work.
* I'm sure that all non-Windows builds make use of their native versions of shared libraries.
* Must I separate my commits into different PRs now?
I will take notice and avoid large and unspecific PR later on.

On StepMania customization, `cmd()` was added as a function and reserved keyword in lua-5.1, and `TryGet()` was added in jsoncpp.

**Comment by Prcuvu** [comment]
I'm now going to clean this up, separating it into specific PRs. This PR will be closed when everything is done.

**Comment by wolfman2000** [comment]
@Prcuvu One of the original points of this PR was to allow for compiling StepMania on Windows with the /MT flag. With the current state of master, does that work yet?

**Comment by Prcuvu** [comment]
@wolfman2000 Not yet. We need `libjpeg`, `libogg` and `libvorbis`. I'm currently working on `libjpeg` (mainly on auto-generation of `jconfig.h`).

**Comment by wolfman2000** [comment]
Remember to avoid modifying files from within wherever you get libjpeg from. Create a dedicated config file in extern if needed: look at what was done with MAD as a reference.

**Comment by Prcuvu** [comment]
Since the tasks are achieved, this PR can be closed now.

**Pull request closed without merging**
