### PR TITLE
Added code to disable x11 dpms on startup and restore it on exit.

### PR DESCRIPTION
**Pull request by kyzentun**
My screen kept going into dpms mode, even while I was playing on keyboard.  So this disables dpms on startup.

### CODE REVIEW

**Comment by shakesoda** [comment]
we probably should've had this a decade ago :+1:

**Comment by kyzentun** [comment]
I never had it go into dpms while playing on keyboard until I moved.  Maybe it was just luck from me checking irc and junk after every song.

I also looked through the X11 man pages and found functions for controlling the screensaver, but
1) I don't have a screensaver.
2) There's already code in stepmania that's supposed to disable the screensaver, and I don't know whether it works.

It's important to know that dpms and screensaver are two different and separated things in x11.

**Comment by nixtrix** [comment]
wow so it turns out the thing that was turning off my display every few minutes even after I kill -9'd my power manager was dpms after all, thanks for letting me know of its existence lol

**Comment by kyzentun** [comment]
I've been using a script that does "xset -dpms s off" for years.

**Pull request merged**
