### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheKamilia**
irc.freenode.net is gone, we need a official discord

### CODE REVIEW

**Comment by ListenerJubatus** [comment]
no it's chat.freenode.net

also we are not getting a Discord. it's closed source.

**Comment by TheKamilia** [comment]
[chat.freenode.net](url) is gone

**Comment by coderjo** [comment]
It is? Weird. My IRC client seems to think it is connected to freenode using that hostname right now.

**Comment by coderjo** [comment]
Note that there is no web server at that address. if you want webchat, use webchat.freenode.net

**Pull request closed without merging**
