### PR TITLE
Bring consistent line endings to our source files.

### PR DESCRIPTION
**Pull request by wolfman2000**
This should finally remove that stain from years ago.

### CODE REVIEW

**Comment by wolfman2000** [comment]
This replaces the `dos2unix` portion from #800.

**Comment by shakesoda** [comment]
Doesn't git have an option to take care of this? I know it does for local checkouts, not sure about just flagging line ending changes in the repo.

**Comment by wolfman2000** [comment]
Remember the `.hgeol` stuff? These files were the only ones that didn't get "fixed" after that I think.

It's more a matter of restoring consistency. It does not have to be merged in.

**Comment by wolfman2000** [comment]
...maybe another day this can be looked at.

**Pull request closed without merging**
