### PR TITLE
Remove bundled FFmpeg

### PR DESCRIPTION
**Pull request by mkroening**
This is my take on resolving #1869. Depends on #1870 for demonstrating successful building and is thus marked as draft. Apart from that this is open for discussion.

## Short summary of the current issue
We currently set up FFmpeg on windows with somewhat recent dynamic libraries and do the copying on our own. On Unix we compile an old version from source having the link arguments hard coded.

### Cons for the dev
* Many options when configuring a build directory
  * `WITH_FFMPEG`, `WITH_FFMPEG_JOBS` only available when not using MSVC.
  * `WITH_SYSTEM_FFMPEG`, `WITH_CRYSTALHD_DISABLED` only available on Linux.
* Not many configurations are supported (windows-static, x86_64-windows are not)
* On Unix when using the bundled FFmpeg we have to recompile it for each new build configuration

### Cons for the maintainers
* High complexity of the build system
* Hard to update the bundled FFmpeg, as hard coding any flags is necessary by the nature of CMake's seperation of configuration phase and build phase

## This approach

This reworks the logic for FFmpeg in our build system to use an supplied toolchain if available and then fall back to system libraries. That allows the use of vcpkg for advanced FFmpeg configuration and reduces the amount of lines of configuration code to about 6. Also FFmpeg is not being rebuilt as part of StepMania.
Then this removes the bundled FFmpeg. Furthermore this makes FFmpeg mandatory (please debate) as this is an expected feature and works on all systems. Last but not least this reworks the README to have working CI badges and updates building instructions for all systems.

What do you think of this? I think it can't get much easier and flexible than this.

### CODE REVIEW

**Comment by mkroening** [comment]
~~@shakesoda, could you also @ Jousway from discord? He said something about FFmpeg in 5.3 and I don't know his GitHub tag.~~

Edit: Nevemind, I guess it's @Jousway. :D

**Comment by shakesoda** [comment]
ffmpeg cannot be mandatory for license reasons.

edit: more specifically, builds with ffmpeg (mad, too) typically have GPL codecs, so builds distributed with it must comply with GPL. this isn't a problem for general packaging, but we explicitly support using stepmania in situations where this doesn't work (i.e. closed source projects).

**Comment by mkroening** [comment]
Thanks for your quick reply!

Ah I see. Vcpkg builds FFmpeg without GPL'ed modules by default, so having it as a dynamic library under LGPL should be no problem for closed source projects, right?

If people want to include GPL'ed modules they can build `ffmpeg[gpl]` with vcpkg, which we probably should do for our builds. See [vcpkg - ffmpeg/CONTROL](https://github.com/microsoft/vcpkg/blob/master/ports/ffmpeg/CONTROL).

Would this be okay for you?

**Comment by shakesoda** [comment]
LGPL would still be an issue for static builds (although, i have no idea if those still work as it stands), so i would still rather the option to disable entirely.

**Comment by mkroening** [comment]
Static builds do work, but closed source projects would be forced to build dynamically of course.

Okay, I'll readd the option. Having `WITH_FFMPEG=ON` by default would be okay, right?

Edit: Static builds should work (verified on windows), but in my opinion dynamic libraries are to be preferred when possible.

**Comment by shakesoda** [comment]
yes, it's perfectly fine as a default.

**Comment by mkroening** [comment]
Sorry for the delay!

I reworked it to include `USE_FFMPEG` which is on by default.
See [Travis](https://travis-ci.com/mwkroening/stepmania/builds/125946425) and [AppVeyor](https://ci.appveyor.com/project/mwkroening/stepmania/builds/27184422) for demonstrating building without FFmpeg.

It's possible to further streamline the CMake structure, but this is not in the scope of this PR.

PS: If this gets merged, please do not squash the commits. That would make a cluttered commit history because of the giant FFmpeg removal commit.

**Comment by mkroening** [comment]
@shakesoda, should we drop Windows XP support with this PR or not?

To elaborate: As with this PR we require FFmpeg (and others in the future) to be supplied via a CMake toolchain file (e.g. from vcpkg) or as system library. Vcpkg does not support building with the `v140_xp` (see: [VCPKG_PLATFORM_TOOLSET](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_platform_toolset)) target neither does FFmpeg since 4.0 (see [FFmpeg changelog](https://ffmpeg.org/#pr4.0)).

For those libraries we could supply a custom CMake toolchain, which basically does what this PR aims to remove and which we'd have to maintain, for Windows XP.
Or we could end official Windows XP support and require any developer targeting XP to supply a custom toolchain file on their own.

What's the way to go for now?

**Comment by mkroening** [comment]
Rebased on latest master, refined wording for building instructions.

**Comment by mkroening** [comment]
@geefr, do you want to test this as well and share your thoughts about it?

Apart from the XP question this is ready for review, but depending on the answer there may be additional changes needed before merging to maintain XP support.

**Comment by geefr** [comment]
The cmake changes look like they should work, I might do it a bit differently but can't complain about those

Otherwise my thoughts are it's a good idea overall, and I'll defer to the stepmania maintainers/regulars for the decisions. Would be good to have a list of supported OSs somewhere if it's not covered by travis, inevitably a change to the build system in codebases like this can cause unexpected issues for someone..

For testing I've got decent VMs/etc so can check pretty much any system setup, but quite busy with beatsaber stuff for the moment :)

**Comment by mkroening** [comment]
Thanks for your answer!

Supported operating systems can be found in the Wiki ([Minimum Requirements](https://github.com/stepmania/stepmania/wiki/Minimum-Requirements)), although that looks a bit outdated.

I tested playing with background videos successfully on Linux and Windows and I am confident that this works on macOS as well.

**Comment by mkroening** [comment]
I'm not actively pursuing this anymore.

**Pull request closed without merging**
