### PR TITLE
Update gtk+ LoadingWindow to use gtk3

### PR DESCRIPTION
**Pull request by leftmostcat**
Primarily changes against CMake, with one change to the code to remove a deprecated symbol. Built and briefly tested. No visible issues.

### CODE REVIEW

**Comment by wolfman2000** [comment]
I'm forced to ask a silly question here. What if someone has GTK2 instead of GTK3? Wouldn't this code break that?

**Comment by shakesoda** [comment]
@wolfman2000 GTK3 has been around since 2011 at this point.

**Comment by shakesoda** [comment]
@leftmostcat I'd put this on the 5.1 branch instead, 5.0 branch (master) is effectively frozen for dependencies.

**Comment by leftmostcat** [comment]
Closing and reopening against 5_1_0. Sorry about the confusion.

**Pull request closed without merging**
