### PR TITLE
macOS Catalina Workarounds

### PR DESCRIPTION
**Pull request by heshuimu**
Relates to #1914 

I "fixed" three macOS API usage issues that are blocking the game from launching. All of them are related to using AppKit API not on the main thread. The game now launches, graphics, audio and input works but I have not test it thoroughly yet. 

There are still issues specific to Catalina:
- When running on a high DPI screen, the app must be set to run in "Low Resolution" Mode or the game would only render in the lower left corner. 
- User must grant StepMania access to "Input Monitoring" in System Preferences otherwise keyboard input would not work.

### CODE REVIEW

**Comment by mattbisme** [comment]
I used your repo to build StepMania with [these steps](https://github.com/stepmania/stepmania/wiki/Compiling-StepMania#macos), but StepMania is still crashing; no log file to be found! Is there something I should be aware of besides what's in the build steps?

**Comment by mattbisme** [comment]
Still not working, but no longer crashing: seems as though you have to reinstall the default theme files and data folder to get it to open. However, now I'm met with a black screen. You can hear the game sounds when navigating the menus. Everything *sounds* like it's running… you just can't see anything. Any thoughts would be great.

**Comment by heshuimu** [comment]
I was debugging on a computer that has never installed any versions of StepMania before. The built app bundle was running directly in the repo root directory, basically a clean install-esque environment. May be your config triggered a different code path that I did not test. 

Can you share your graphics settings? What resolution did you use, and did you enable full screen?

I don't think StepMania emit stacktraces upon crashing, but you can use Xcode to capture one, which is 100x helpful for debugging crashes. I'll post the instruction later here.

**Comment by quietly-turning** [comment]
Popping in to to note that I built from @heshuimu's catalina-workaround branch and it works as described.

For any input to register, StepMania must be whitelisted under 
System Preferences → Security & Privacy → Privacy (tab) → Input Monitoring

Screen Shot 2019-11-16 at 10 50 07 AM

You can right-click on the resulting StepMania.app, choose *Get Info*, and check *Open in Low Resolution* to "fix" rendering on retina displays.

Screen Shot 2019-11-16 at 10 51 59 AM

Without this, StepMania will only draw to the lower-left quadrant of its window on retina displays.

Screen Shot 2019-11-16 at 10 57 26 AM

In all, thank you for this @heshuimu.💛 

---

I found that StepMania crashes if I drag the window from one display to another.  For me, this is one high DPI screen (my MacBook Pro's built-in display) and one non-high DPI display.

No crashinfo.txt is generated at `~./Library/Logs/StepMania 5.1/crashinfo.txt`. 
Xcode's general log output looks like:
```
LoadNoteSkinDataRecursive: common (NoteSkins/common/common/)
Load script "NoteSkins/common/common/NoteSkin.lua"
Load script "NoteSkins/dance/default/NoteSkin.lua"
Load script "NoteSkins/common/common/NoteSkin.lua"
Load script "NoteSkins/dance/vivid/NoteSkin.lua"
Looking for a card for Player 1
Looking for a card for Player 2
Zeroing this update.  Was 0.197771
Fatal: crash from within the crash signal handler
Program ended with exit code: 1
```

---

> now I'm met with a black screen. You can hear the game sounds when navigating the menus. Everything sounds like it's running… you just can't see anything. Any thoughts would be great.

@mattbisme - This sounds like https://github.com/stepmania/stepmania/issues/1761

---

>  seems as though you have to reinstall the default theme files and data folder to get it to open.

This sounds like it might be an alternative approach to [step 6]( https://github.com/stepmania/stepmania/wiki/Installing-on-macOS#6-remove-quarantine-extended-attribute-from-sm51) of the wiki guide for Installing on macOS.

**Comment by heshuimu** [comment]
Happy to contribute. 😄
I'll try to recreate the mixed DPI situation and see what I can find.

**Comment by mattbisme** [comment]
I have, unfortunately, only had regressions since trying additional steps to get StepMania to launch. I knew about the Input Monitoring requirement, as well as low resolution mode, so that leaves configuration (unless I'm missing something).

I have now deleted all of the known locations where configuration files are generated (`~/Library/Application Support/`, `~/Library/Preferences/`), and followed the build steps once again from scratch. This time, more closely following the installation guid that includes removing the quarantine attribute (instead of replacing the folders). 

However, to my surprise, I'm still getting crashes. I can't even get the "black screen" issue anymore! At least that one *sounded* functional. So, I'm really at a loss as to what I should try next. 

I did find the log file though. There seem to be a number of warnings in there. I will attach it just in case is proves to be useful. 
[log.txt](https://github.com/stepmania/stepmania/files/3855161/log.txt)

**Comment by mattbisme** [comment]
Looks like I found the issue! Embarrassingly fundamental, but then again, I don't use git all that often. I was following the build steps a bit *too* closely. That is, 
```bash
git clone --depth=1 https://github.com/heshuimu/stepmania.git
```
really needed to be 

```bash
git clone --single-branch -b catalina-workaround --depth=1 https://github.com/heshuimu/stepmania.git
```
After that, everything else worked as expected with one exception: input monitoring. Despite StepMania being listed, and despite being able to right click on it (in the exceptions list), "Show in Finder," and see that it's pointed to the correct .app… keyboard input would not work until I removed it from the list and added it again. Probably good knowledge to have for the future, at least. 

**Update**: clicking the green "maximize" button crashes StepMania immediately.

**Comment by Tatsh** [comment]
I am interested in following this conversation as I maintain a [Portfile for MacPorts](https://github.com/Tatsh/ports/blob/master/games/stepmania/Portfile) which allows easy installation. Happy to test and fix issues. I will be using this patch for the time being.

If there is not going to be a fix for the low resolution issue, you should be setting `NSHighResolutionCapable` to `<false/>` in the `Info.plist`. This removes the need to set it manually in Finder.

**Comment by Tatsh** [comment]
@heshuimu add this to `Xcode/Info.plist.in.xml`:

```
diff --git a/Xcode/Info.plist.in.xml b/Xcode/Info.plist.in.xml
index 34d6ffee4d..4b911aa973 100644
--- a/Xcode/Info.plist.in.xml
+++ b/Xcode/Info.plist.in.xml
@@ -55,6 +55,8 @@
     <string>Copyright 2001-2015</string>
     <key>NSPrincipalClass</key>
     <string>SMApplication</string>
+    <key>NSHighResolutionCapable</key>
+    <false />
   </dict>
 </plist>
 
```

**Comment by heshuimu** [comment]
I will. I’ll push the changes.

**Comment by Tatsh** [comment]
Unfortunately due to the way TCC works (probably by hashing / check code signature for App Store apps), after every build you have to go and uncheck and check StepMania in System Settings. And you won't get a message from TCC after the first run even if the binary has changed.

**Comment by ColonelPanics** [comment]
Thank you so much for this! Cloned the repo, followed instructions and _it only bloody works!_

For some reason the escape key doesn't get recognised by the game when I've got a BetterTouchTool touchbar loaded but toggling back to regular Apple touchbar works around this.

**Comment by avielg** [comment]
So I can finally launch (thanks @heshuimu !!) but:
- When trying to drag the window size and/or go "mac" fullscreen (with the green dot on the top) I crash instantly.
- When switching to fullscreen via the menu I get a black screen (I can hear the game in the background but see nothing)
- and weirdest: my DDR pads work everywhere except in the game selection menu! in there if I even touch any of the pads I instantly crash! so I have to pick a song with the MacBook keyboard and only get on the pads when the game begins (very specific combination of touching at first to get to 2 players mode, then not touching to pick a song, then opening options to change players difficulty, cuz double-down in songs list would crash). Once im in the song it works great (I just have to get off the pad when the song ends or it crash again...).

Tried to crash when running from Xcode but I don't really get anything useful, just this:
```
Fatal: crash from within the crash signal handler
Program ended with exit code: 1
```
any way to get better log? or anyone else experienced this?

**Comment by heshuimu** [comment]
Crashing on full-screen and changing monitor is expected. I was only fixing crashes by the code path that I have run into. I don't have time to look deeper into this recently, but I will come back to this eventually. 

The core issue is that Apple now mandates UI-related AppKit API to be called on main thread. The temporary fix is to wrap any offending calls in `dispatch_sync`.

**Comment by quietly-turning** [comment]
@avielg – Some of the problems you are describing have already been discussed earlier in this thread. I linked to existing GitHub issues where possible.

---

Thank you for getting it even this far, @heshuimu.  I'm sure the macOS-based StepMania enthusiasts of the world are grateful for your help. 💛

**Comment by samdoctor** [comment]
This branch fixes issues on Catalina for me. (Crashing on start) However, it still crashes when I try to resize or go full screen. Is there another ticket for that?

**Comment by heshuimu** [comment]
Hi all, I have come around to add a workaround for a crash that occurs when using the native window control to full screen (the green button). 

The in-game full screen setting is not working. Every time I set it, the screen becomes pitch black, and I can't do anything unless I Command+Q the game. The game itself is running and I can hear UI sound when I press arrow keys, but I cannot figure out why the screen goes dark.

**Comment by heshuimu** [comment]
~~I also noticed that in order to avoid the Input Monitoring permission, macOS apps may have to use App Sandbox entitlement.~~ Setting this, however, would certainly break the game asset discovery mechanism. This could be an issue in the future if Apple chooses to enforce App Sandbox. 😵

**Comment by Tatsh** [comment]
@heshuimu Not really. The assets should go elsewhere, like `~/Library/Application Support/StepMania`. The default assets would still be in the app bundle. Having the data next to the app bundle is very unusual for any macOS app.

**Comment by heshuimu** [comment]
> @heshuimu Not really. The assets should go elsewhere, like `~/Library/Application Support/StepMania`. The default assets would still be in the app bundle. Having the data next to the app bundle is very unusual for any macOS app.

This is a way to go, but I don't know how much work is needed to implement this platform-specific in this project. I'll see if I can find more info.

**Comment by quietly-turning** [comment]
> The assets should go elsewhere, like `~/Library/Application Support/StepMania`.

> I don't know how much work is needed to implement this platform-specific in this project.

I'm unable to track this conversation 100%, so I'll just link to the lines in ArchHooks where user data locations on macOS seem to be defined in the hope that it helps someone:  https://github.com/stepmania/stepmania/blob/35b557b8d6aacfcd399a28cb934374366a01deed/src/arch/ArchHooks/ArchHooks_MacOSX.mm#L337-L350

**Comment by Tatsh** [comment]
Yes that is the place to put this change. I spoke to shakesoda already about this. He said anyone who wants to should do it. We already put things in ~/.StepMania-* on both Linux and macOS. Better to use standard locations.

**Comment by heshuimu** [comment]
The code indeed help me packaging the default resources into app bundle and read it back correctly. But sandboxing the app with USB entitlement did not help getting rid of the input monitoring permission.

**Comment by coderjo** [comment]
5.1 on MacOS already uses the various standard locations. See the function MountUserFilesystems here:

https://github.com/stepmania/stepmania/blob/5_1-new/src/arch/ArchHooks/ArchHooks_MacOSX.mm#L329

**Comment by Tatsh** [comment]
Then it's already done. I would recommend making it use a version name suffix for non-stable versions like Beta, after the product ID. This way unstable versions can run alongside stable.

**Comment by heshuimu** [comment]
@Tatsh @quietly-turning @coderjo 
I updated CMakeList and code to copy and use default resources in the app bundle --> https://github.com/stepmania/stepmania/pull/1933/commits/6b524a6c1fd8867eaf2bc6fb12bffae816376e86

----------

I also wrote a simple NSEvent-based keyboard input as an answer to not having keyboard inputs without Input Monitoring privilege. The only thing I cannot get working is the key down event for keys other than modifier keys like shift and control.

**Comment by samdoctor** [comment]
Are there any settings on the computer that might be preventing the app from starting? One minute it was working, then I came back to my laptop a little later and it was not. (I see the black screen for a split second before it crashes)

I tried different display settings, and removing `~/Library/Application Support/, ~/Library/Preferences/` 

system.log shows
`com.apple.xpc.launchd[1] (com.StepMania-5.7288[11960]): Service exited with abnormal code: 1`

And here is the [log.txt](https://github.com/stepmania/stepmania/files/3995851/log.txt)

Attaching .crash file as well
[StepMania_2019-12-24-122957_Samuels-MacBook-Pro.txt](https://github.com/stepmania/stepmania/files/3998880/StepMania_2019-12-24-122957_Samuels-MacBook-Pro.txt)

**Comment by Tatsh** [comment]
It's impossible to tell where but it crashed inside of [`RageDisplay_Legacy::EndFrame()`](https://github.com/stepmania/stepmania/blob/5_1-new/src/RageDisplay_OGL.cpp#L851). This is the relevant part of the stack trace:

```
10  com.StepMania-5               	0x000000010e770a2a RageDisplay_Legacy::EndFrame() + 602
11  com.StepMania-5               	0x000000010e77039c RageDisplay_Legacy::ResolutionChanged() + 28
12  com.StepMania-5               	0x000000010e770606 RageDisplay_Legacy::TryVideoMode(VideoModeParams const&, bool&) + 566
13  com.StepMania-5               	0x000000010e76665f RageDisplay::SetVideoMode(VideoModeParams, bool&) + 79
14  com.StepMania-5               	0x000000010e76e6ab RageDisplay_Legacy::Init(VideoModeParams const&, bool) + 235
```

Seems to have to do with the video mode Stepmania is trying to use on your system. Perhaps a macOS update broke something? Or it could be caused by the integrated graphics card (assuming your system has that).

**Comment by cjlint** [comment]
+1 that this branch works for me! Although only after I realized that I need to build StepMania with
```
xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
```
to avoid `codesign` failures

**Comment by Sappharad** [comment]
Not sure if this is known or not, but using a USB dance pad seems to crash with these fixes. It worked fine on StepMania 5 under Mojave. Specifically, everything works fine on the menus and you can map buttons & navigate with the dance pad fine but as soon as you get to the song select screen and press any button on the dance pad the app crashes.

Stack Trace:
> Thread 1 Crashed:
0   com.StepMania-5               	0x000000010546585d CrashHandler::CrashSignalHandler(int, __siginfo*, __darwin_ucontext const*) + 253
1   com.StepMania-5               	0x000000010544030b DoCrashSignalHandler(int, __siginfo*, __darwin_ucontext const*) + 27
2   com.StepMania-5               	0x0000000105467aec SigHandler(int, __siginfo*, void*) + 76
3   libsystem_platform.dylib      	0x00007fff6c0db42d _sigtramp + 29
4   ???                           	000000000000000000 0 + 0
5   com.StepMania-5               	0x00000001054657ea CrashHandler::CrashSignalHandler(int, __siginfo*, __darwin_ucontext const*) + 138
6   com.StepMania-5               	0x000000010544030b DoCrashSignalHandler(int, __siginfo*, __darwin_ucontext const*) + 27
7   com.StepMania-5               	0x0000000105467aec SigHandler(int, __siginfo*, void*) + 76
8   libsystem_platform.dylib      	0x00007fff6c0db42d _sigtramp + 29
9   ???                           	000000000000000000 0 + 0
10  libdispatch.dylib             	0x00007fff6be8a72e dispatch_assert_queue + 122
11  com.apple.HIToolbox           	0x00007fff33394952 islGetInputSourceListWithAdditions + 119
12  com.apple.HIToolbox           	0x00007fff33397134 isValidateInputSourceRef + 90
13  com.apple.HIToolbox           	0x00007fff33396ffc TSMGetInputSourceProperty + 30
14  com.StepMania-5               	0x000000010544961c KeyCodeToChar(unsigned short, unsigned int) + 60
15  com.StepMania-5               	0x00000001054495c1 InputHandler_MacOSX_HID::DeviceButtonToChar(DeviceButton, bool) + 145
16  com.StepMania-5               	0x0000000105376718 ScreenSelectMusic::Input(InputEventPlus const&) + 1064
17  com.StepMania-5               	0x00000001052f6d95 ScreenManager::Input(InputEventPlus const&) + 261
18  com.StepMania-5               	0x00000001053ecbe4 HandleInputEvents(float) + 724
19  com.StepMania-5               	0x0000000104fc5eac GameLoop::UpdateAllButDraw(bool) + 604
20  com.StepMania-5               	0x0000000104fc6db7 GameLoop::RunGameLoop() + 3751
21  com.StepMania-5               	0x00000001053eb328 sm_main + 8680
22  com.StepMania-5               	0x0000000105462c52 -[SMMain startGame:] + 18
23  com.apple.Foundation          	0x00007fff36ed87a8 __NSThread__start__ + 1064
24  libsystem_pthread.dylib       	0x00007fff6c0e6e65 _pthread_start + 148
25  libsystem_pthread.dylib       	0x00007fff6c0e283b thread_start + 15

The fact that it works prior to that screen is promising, I haven't looked at the code yet to see if anything seems like an obvious cause. Just to clarify, I am running Catalina. The same setup worked fine on the previous releases prior to Catalina.


Edit: If I completely comment out the "// Use Text Input Source services to convert the key code to character code." section of InputHandler_MacOSX_HID.cpp then it no longer crashes and the game is playable with a USB dance pad. But that stops keyboard from working. I'm guessing the problem has something to do with all input being passed through this method instead of just keyboard input.

I don't know if this is a 'proper' fix, but changing line 450 from
`	if( KeyboardDevice::DeviceButtonToMacVirtualKey( button, iMacVirtualKey ) )`
to
`	if((button < JOY_LEFT || button > JOY_BUTTON_32) && KeyboardDevice::DeviceButtonToMacVirtualKey( button, iMacVirtualKey ) )`
also fixes the problem, but I can't get keyboard support to work at all anymore now, just my USB dance pad. I'm positive I didn't change any other code. Does assigning the USB pad buttons in options wipe out keyboard inputs?

Since I have a build with a fix that works for me (but potentially breaks other things?) I'm satisfied with this fix and won't touch it further. But I figured it was worth documenting in this thread in case someone knows a proper way to fix it.

**Comment by Ratchette** [comment]
I can't seem to get my mac running Catalina 10.15.3 to run the newly built stepmania application. 

I'm following the work arounds in this thread:
- using the catalina-workaround branch
- building using the command in https://github.com/stepmania/stepmania/pull/1933#issuecomment-592917640

But my mac is reporting that the newly built binary may be "damaged or incomplete".
Screenshot 2020-03-25 at 00 17 34

Would you happen to have any ideas as to what could be causing this error?

**Comment by Sappharad** [comment]
> I can't seem to get my mac running Catalina 10.15.3 to run the newly built stepmania application.

Mine did the same thing. Build it in release mode instead, that works.

**Comment by Ratchette** [comment]
Release mode did the trick. Thank you @Sappharad!

**Comment by cptnobvs** [comment]
> > I can't seem to get my mac running Catalina 10.15.3 to run the newly built stepmania application.
> 
> Mine did the same thing. Build it in release mode instead, that works.

I have been following this approach. Stepmania starts loading songs, but the program does not start once the songs finish loading. Here's the output from my logs.txt:

`
00:00.085: StepMania5.1-git-aae68b4
00:00.085: Compiled 20200324 @ 01:59:46 (build aae68b4)
00:00.085: Log starting 2020-03-24 19:18:57
00:00.085:
00:00.085: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.086: Reading 'Data/Static.ini' failed: No such file or directory
00:00.086: Reading 'Data/Static.ini' failed: No such file or directory
00:00.086: Loading window: macosx
00:00.086: Model: MacBookPro15,1 (16/16)
00:00.086: Clock speed 2.40 GHz
00:00.086: Mac OS X 10.15.2
00:00.086: Memory: 32.00 GB
00:00.087: ThemeManager::SwitchThemeAndLanguage: "default", "en"
00:00.096: Loading "/Scripts/32log.lua" ...
...
...
...
00:00.113: Loading "/Themes/default/Scripts/04 Other.lua" ...
/////////////////////////////////////////
00:00.147: WARNING: Couldn't get available nominal sample rates info: 'nope' (1852797029).
/////////////////////////////////////////
00:00.148: Starting thread: Decode thread
00:00.148: Sound driver: AudioUnit
00:00.148: Starting thread: Music thread
00:00.149: Number of Coins to Load on boot: 0
00:00.149: Initializing lights drivers: SystemMessage,Export
00:00.149: Lights driver: SystemMessage
`

Any ideas why the program isn't starting?

**Comment by cptnobvs** [comment]
I ended up trying to launch the program by opening the file `stepmania/StepMania.app/Contents/MacOS/StepMania`. I see the following error message in the terminal that opens:

```
StepMania5.1-git-aae68b4
Compiled 20200325 @ 00:26:08 (build aae68b4)
Log starting 2020-03-25 17:54:16
Loading window: macosx
Model: MacBookPro15,1 (16/16)
Clock speed 2.40 GHz
Mac OS X 10.15.2
Memory: 32.00 GB
/////////////////////////////////////////
WARNING: Couldn't get available nominal sample rates info: 'nope' (1852797029).
/////////////////////////////////////////
Sound driver: AudioUnit
Lights driver: SystemMessage
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: stoi: no conversion
Fatal: crash from within the crash signal handler

[Process completed]
```

Looks like there's something wrong with my C++ library. Any ideas on how to fix it?

**Edit**

I ended up recloning the repo, deleting my `~/Library/Application Support/Stepmania 5/` folder, and rebuilding. Now Stepmania launches, but I can't give any input. Here's the error message:

```
OpenGL Windowed 1680x1028 32 color 16 texture 60Hz Vsync SmoothLines
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Failed to open the interface. - (iokit/common) not permitted(e00002e2,738)
/////////////////////////////////////////
Mixing 1068.251709 ahead in 3942 Mix() calls
Players joined: none
Language: en
Current renderer: OpenGL
Theme: default

[Process completed]

```
Any ideas here? Sorry for spamming this PR.

**Comment by cptnobvs** [comment]
I got it working. The fix was to delete my Stepmania folder, delete `~/Library/Preferences/Stepmania`, delete `~/Library/Application\ Support/Stepmania`, and `~/Library/Caches/Stepmania`. I then recloned the repo with this PR's branch, followed the build steps up until the final step where I used this command:
`xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -configuration Release
`
Now the program works. It crashes after a few songs when it gets back to the song select screen, but it can start again no problem. Also there seems to be a bug where if I add certain songs to the Songs folder the program crashes instantly on load.

**Comment by coderjo** [comment]
the stoi exception isn't your c++ library. The game is attempting to convert a string to an integer, but it was using something that is not numeric. Likely it was loading a value from a step file or something like that.

**Comment by Tatsh** [comment]
> the stoi exception isn't your c++ library. The game is attempting to convert a string to an integer, but it was using something that is not numeric. Likely it was loading a value from a step file or something like that.

I actually got this same crash on Linux today after pulling the latest code. I reset my config and that worked, so then I put my songs back and the crash was back. Not sure yet what song is causing the crash but I've narrowed it down to a subset.

**Comment by heshuimu** [comment]
I'm closing this as 5.3 would have better support.

**Comment by bkirz** [comment]
👋 Hi! I found this issue while trying to build 5.1 for my new machine running Catalina. While I understand that 5.3 has also built support for Catalina, I think it's worth pursuing a fix in this branch as well. I'm excited to see the results of the 5.3 project, but it's not currently open source and the only plan to release the source is "when it's ready." The theme I'd like to use, Simply Love, is not yet supported for 5.3 for that reason, so right now my only option for this machine is to get a working 5.1 build. Would y'all consider reopening this PR?

**Comment by concubidated** [comment]
@bkirz  The amount of work that went into 5.3 to get it working correctly on OSX, is not really something that is easily PR'd into 5.1. (The entire input system was rewritten for example)

You can just hit escape on the warning error on SL on 5.3 to get past that (or remove the check from the theme). There is no incompatibility there.

**Comment by quietly-turning** [comment]
> Would y'all consider reopening this PR?

I've been respecting @heshuimu's wishes that this pull request be closed.

**Comment by bkirz** [comment]
Thanks for the quick replies!

> The amount of work that went into 5.3 to get it working correctly on OSX, is not really something that is easily PR'd into 5.1.

Gotcha. I wasn't expecting the solution to be to backport 5.3's fixes, especially since that's not possible without the source code. I'm hopeful that the amount of work required to bring compat to 5.1 is less than a full input system rewrite.

> You can just hit escape on the warning error on SL on 5.3 to get past that (or remove the check from the theme). There is no incompatibility there.

I still have some FUD around lack of intent to stay compatible given the warning; even if it's compatible now, there's no guarantee that compat issues in the future will be fixed. Also, I'm generally uncomfortable relying on alpha builds of closed source software. Given the lack of a timeline for a stable release of 5.3 or its source, I'd prefer to stick to fixing 5.1.

> I've been respecting @heshuimu's wishes that this pull request be closed.

That makes sense! I misread the end of the PR and didn't realize it had been closed by the submitter. In that case, I'd like to take a stab at finishing the catalina fixes (although I'm new to both macOS development and the Stepmania codebase and can't commit any sort of timeline yet). Would a PR that cherry picks from this branch and builds upon it be welcome?

**Comment by quietly-turning** [comment]
@bkirz – I'm also in favor of fixing 5.1 for the time being.  Thanks for offering to help out!

As is, the work done here by heshuimu accomplishes the basic goal of getting SM5.1 (as recently as 7b4e4f81d0aeb46f010c1327b92193c3ad8ae5bf) playable on macOS Catalina.  Various macOS issues (lack of high DPI/retina support, input monitoring permissions with Catalina, code signing, inconsistently implemented full screen support, etc.) still remain, so maybe it makes sense to open a new issue (so we don't keep pinging heshuimu) describing what you hope to accomplish with your proposed PR.

I'm definitely interested in discussing this.

**Comment by bkirz** [comment]
> maybe it makes sense to open a new issue (so we don't keep pinging heshuimu) describing what you hope to accomplish with your proposed PR.

Circling back on this since it's been a few days: I was hoping to have a PR up by now to stop pinging everyone else in this one, but I'm still figuring out the dev workflow to get that set up. (I'm familiar with github, but my normal workflow is single-repo and life's been getting in the way of sitting down and figuring it out in one session). Hoping to have something ready in the next few days to continue the discussion, likely starting with the same initial set of commits as this PR.

**Comment by heshuimu** [comment]
> The amount of work that went into 5.3 to get it working correctly on OSX, is not really something that is easily PR'd into 5.1. (The entire input system was rewritten for example)

I would actually support 5.3 superseding 5.1.

**Pull request closed without merging**
